[Export]
baked_state = false
offer_binder = true
ignore_cache = [
    "index.jl",
]

# [Precompute]
# enabled = true
# max_filesize_per_group = 20000000 # 20 MB

[SliderServer]
exclude=[
    "index.jl",
]
